version: 2
jobs:
  build:
    docker:
      - image: francoischabot/easy_grpc_buildenv:latest

    steps:
      - checkout

      - run:
          name: Create build script
          command: |
            mkdir _bld 
            cd _bld 
            cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=1 ..

      - run:
          name: Build
          command: |
            cd _bld 
            make -j $(nproc)

      - run:
          name: Test
          command: |
            cd _bld 
            ctest -T memcheck

      - run:
          name: Coverage
          command: |
            coveralls --build-root build \
              -e build/external \
              -e build/include \
              -e build/CMakeFiles/3.12.1 \
              -e build/CMakeFiles/feature_tests.c \
              -e build/CMakeFiles/feature_tests.cxx