version: 2
jobs:
  build:
    docker:
      - image: francoischabot/easy_grpc_buildenv:latest

    steps:
      - checkout

      - run:
          name: Create build script
          command: |
            mkdir _bld 
            cd _bld 
            cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=1 ..

      - run:
          name: Build
          command: |
            cd _bld 
            make -j $(nproc)

      - run:
          name: Test
          command: |
            cd _bld 
            ctest -j $(nproc) -T memcheck

      - run:
          name: Coverage
          command: |
            coveralls --gcov-options '\-lp' --build-root _bld \
              -e examples \
              -e tests/generated \
              -e protoc_plugin \
              -e _bld/external \
              -e _bld/include \
              -e _bld/CMakeFiles/3.12.1 \
              -e _bld/CMakeFiles/feature_tests.c \
              -e _bld/CMakeFiles/feature_tests.cxx